---
abstract: 'simple time sequence base on Date::Calc'
author:
  - 'abbypan <abbypan@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-Sequence
requires:
  Date::Calc: '0'
version: '0.01'
